// AUTO-GENERATED by tools/build_json.py — do not edit by hand.
window.CIF = {
  "meta": {
    "schema": "cif-export/1",
    "generated": "2026-07-23 22:04 UTC",
    "projects": 26,
    "deep": 12,
    "summary": 14,
    "sentiment": 0,
    "patterns": 6,
    "source": "examples/DatasetIndex.md + examples/PatternRegistry.md + examples/Sentiment/"
  },
  "projects": [
    {
      "n": "Ethereum",
      "tier": "Deep",
      "file": "examples/CaseStudies/Ethereum.md",
      "cat": "Layer 1 / Smart-Contract Platform",
      "era": "2013–",
      "tags": [
        "l1",
        "first-mover",
        "modular",
        "governance",
        "l2"
      ]
    },
    {
      "n": "Solana",
      "tier": "Deep",
      "file": "examples/CaseStudies/Solana.md",
      "cat": "Layer 1 / High-Performance Monolithic Platform",
      "era": "2017–",
      "tags": [
        "l1",
        "first-mover",
        "modular",
        "monolithic",
        "l2"
      ]
    },
    {
      "n": "BNB Chain",
      "tier": "Deep",
      "file": "examples/CaseStudies/BNBChain.md",
      "cat": "Layer 1 EVM (Exchange-backed) + modular suite (opBNB/Greenfield)",
      "era": "2017–",
      "tags": [
        "l1",
        "first-mover",
        "modular",
        "l2"
      ]
    },
    {
      "n": "Cardano",
      "tier": "Deep",
      "file": "examples/CaseStudies/Cardano.md",
      "cat": "Layer 1 / Peer-reviewed EUTXO platform (Ouroboros PoS)",
      "era": "2015–",
      "tags": [
        "l1",
        "first-mover",
        "modular"
      ]
    },
    {
      "n": "Avalanche",
      "tier": "Deep",
      "file": "examples/CaseStudies/Avalanche.md",
      "cat": "Layer 1 / Metastable-consensus multi-chain (Subnet/L1) + RWA-TradFi",
      "era": "2018–",
      "tags": [
        "l1",
        "first-mover",
        "pivot"
      ]
    },
    {
      "n": "Polkadot",
      "tier": "Deep",
      "file": "examples/CaseStudies/Polkadot.md",
      "cat": "Layer 0 / Heterogeneous-sharding + shared-security (Relay/parachains)",
      "era": "2016–",
      "tags": [
        "l1",
        "first-mover",
        "monolithic",
        "shared-security",
        "l2"
      ]
    },
    {
      "n": "Cosmos",
      "tier": "Deep",
      "file": "examples/CaseStudies/Cosmos.md",
      "cat": "Layer 0 / Appchain \"Internet of Blockchains\" (CometBFT/SDK/IBC)",
      "era": "2014–",
      "tags": [
        "l1",
        "first-mover",
        "modular",
        "governance"
      ]
    },
    {
      "n": "dYdX",
      "tier": "Deep",
      "file": "examples/CaseStudies/dYdX.md",
      "cat": "DeFi / Perp-derivatives DEX (order-book appchain → RWA pivot)",
      "era": "2017–",
      "tags": [
        "defi",
        "first-mover",
        "amm",
        "perps",
        "pivot",
        "l2",
        "l1"
      ]
    },
    {
      "n": "Aave",
      "tier": "Deep",
      "file": "examples/CaseStudies/Aave.md",
      "cat": "DeFi / Money-market lending (Flash Loans, GHO, V4 Hub-and-Spoke)",
      "era": "2017–",
      "tags": [
        "defi",
        "first-mover",
        "modular",
        "stablecoin",
        "l2"
      ]
    },
    {
      "n": "ether.fi",
      "tier": "Deep",
      "file": "examples/CaseStudies/EtherFi.md",
      "cat": "DeFi / Liquid Restaking (LRT) + DeFi Neobank (Stake/Liquid/Cash)",
      "era": "2022–",
      "tags": [
        "defi",
        "lrt",
        "liquid-restaking",
        "restaking",
        "first-mover",
        "bridge",
        "nft-community",
        "shared-security"
      ]
    },
    {
      "n": "EigenLayer",
      "tier": "Deep",
      "file": "examples/CaseStudies/EigenLayer.md",
      "cat": "Infrastructure / Restaking pioneer → EigenCloud (verifiable AI/compute)",
      "era": "2021–",
      "tags": [
        "restaking",
        "efficiency",
        "points",
        "lrt",
        "liquid-restaking",
        "looping",
        "first-mover",
        "shared-security",
        "pivot",
        "l2"
      ]
    },
    {
      "n": "Celestia",
      "tier": "Deep",
      "file": "examples/CaseStudies/Celestia.md",
      "cat": "Modular / Data Availability (sovereign alt-DA; DAS/NMT; Fibre 1 Tb/s)",
      "era": "2019–",
      "tags": [
        "modular",
        "da",
        "first-mover",
        "pivot",
        "l2"
      ]
    },
    {
      "n": "Synthetix",
      "tier": "Summary",
      "file": "examples/Pioneer/Synthetix.md",
      "cat": "DeFi (DeFi Pioneer)",
      "era": "2017–",
      "tags": [
        "defi",
        "first-mover",
        "modular",
        "stablecoin",
        "governance",
        "pivot",
        "l2"
      ]
    },
    {
      "n": "Helium",
      "tier": "Summary",
      "file": "examples/Pioneer/Helium.md",
      "cat": "DePIN (IoT & Wireless)",
      "era": "2013–",
      "tags": [
        "depin",
        "multi-token",
        "fee-burn",
        "governance",
        "mining",
        "l1"
      ]
    },
    {
      "n": "Arweave / AO",
      "tier": "Summary",
      "file": "examples/Pioneer/Arweave-AO.md",
      "cat": "Data Availability / Modular Compute",
      "era": "2017–",
      "tags": [
        "modular",
        "mining"
      ]
    },
    {
      "n": "Farcaster",
      "tier": "Summary",
      "file": "examples/Pioneer/Farcaster.md",
      "cat": "Social (Decentralized Social)",
      "era": "2020–",
      "tags": [
        "social",
        "points"
      ]
    },
    {
      "n": "MakerDAO / Sky",
      "tier": "Summary",
      "file": "examples/Pioneer/MakerDAO-Sky.md",
      "cat": "DeFi (Decentralized Central Bank)",
      "era": "2015–",
      "tags": [
        "defi",
        "stablecoin",
        "governance",
        "pivot"
      ]
    },
    {
      "n": "Safe",
      "tier": "Summary",
      "file": "examples/Pioneer/Safe.md",
      "cat": "Wallet / Account Abstraction",
      "era": "2017–",
      "tags": [
        "wallet",
        "airdrop",
        "governance",
        "pivot"
      ]
    },
    {
      "n": "Chainlink",
      "tier": "Summary",
      "file": "examples/Pioneer/Chainlink.md",
      "cat": "Oracle",
      "era": "2017–",
      "tags": [
        "oracle",
        "infra",
        "bridge"
      ]
    },
    {
      "n": "LayerZero",
      "tier": "Summary",
      "file": "examples/Pioneer/LayerZero.md",
      "cat": "Bridge / Interoperability",
      "era": "2021–",
      "tags": [
        "bridge",
        "interop",
        "airdrop",
        "oracle",
        "sybil"
      ]
    },
    {
      "n": "Lido",
      "tier": "Summary",
      "file": "examples/Pioneer/Lido.md",
      "cat": "Liquid Staking",
      "era": "2020–",
      "tags": [
        "liquid-staking",
        "efficiency",
        "governance"
      ]
    },
    {
      "n": "Uniswap",
      "tier": "Summary",
      "file": "examples/Pioneer/Uniswap.md",
      "cat": "DeFi / AMM",
      "era": "2018–",
      "tags": [
        "defi",
        "airdrop",
        "amm",
        "oracle",
        "governance",
        "mining"
      ]
    },
    {
      "n": "World Network (Worldcoin)",
      "tier": "Summary",
      "file": "examples/Pioneer/WorldNetwork-Worldcoin.md",
      "cat": "Identity",
      "era": "2019–",
      "tags": [
        "identity",
        "sybil",
        "pivot",
        "l2"
      ]
    },
    {
      "n": "Ethena",
      "tier": "Summary",
      "file": "examples/Pioneer/Ethena.md",
      "cat": "DeFi / Stablecoin",
      "era": "2023–",
      "tags": [
        "defi",
        "airdrop",
        "points",
        "perps",
        "stablecoin",
        "synthetic"
      ]
    },
    {
      "n": "Berachain",
      "tier": "Summary",
      "file": "examples/Pioneer/Berachain.md",
      "cat": "Layer 1 (Proof-of-Liquidity)",
      "era": "2021–",
      "tags": [
        "l1",
        "airdrop",
        "stablecoin",
        "meme",
        "nft-community"
      ]
    },
    {
      "n": "Optimism",
      "tier": "Summary",
      "file": "examples/Pioneer/Optimism.md",
      "cat": "Layer 2 (OP Stack / Superchain)",
      "era": "2019–",
      "tags": [
        "l2",
        "airdrop",
        "modular",
        "bridge",
        "governance"
      ]
    }
  ],
  "patterns": [
    {
      "id": "P1",
      "nm": "Efficiency → Concentration → Mitigation",
      "triggers": [
        "liquid-staking",
        "restaking",
        "efficiency"
      ],
      "instances": 3,
      "confidence": "HIGH",
      "analogs": [
        "Lido",
        "EigenLayer",
        "Ethereum"
      ],
      "src": "examples/CaseStudies/CrossAnalysis-ETH-Lido-EigenLayer.md",
      "val": "",
      "pred": "Jika menang di efisiensi modal, sumber daya (stake) akan terkonsentrasi → muncul kekhawatiran sentralisasi & dorongan mitigasi terdistribusi (mis. DVT). Nilai harus dinilai bersama ada/tidaknya mitigasi.",
      "watch": [
        "dominance > ~1/3 dari share",
        "absennya mitigasi desentralisasi"
      ],
      "scope": "Berlaku pada era pasca-Merge (2022–sekarang) di mana solo-staking berbiaya tinggi (32 ETH) mendorong agregasi; bergantung pada masih adanya friksi solo-staking dan minimnya regulasi anti-konsentrasi. Belum diuji di rezim regulasi yang membatasi staking-pool."
    },
    {
      "id": "P2",
      "nm": "Rehypothecation → Correlated Cascading Failure",
      "triggers": [
        "restaking",
        "lrt",
        "looping",
        "liquid-restaking"
      ],
      "instances": 3,
      "confidence": "HIGH",
      "analogs": [
        "EigenLayer",
        "ether.fi",
        "Ethereum"
      ],
      "src": "examples/CaseStudies/CrossAnalysis-ETH-Lido-EigenLayer.md",
      "val": "Renzo ezETH depeg Apr 2024 (~$688, >$65jt liquidations)",
      "pred": "Menggunakan ulang aset yang sama menaikkan yield sekaligus korelasi kegagalan. Risiko depeg + cascading liquidations saat leverage looping unwinding.",
      "watch": [
        "LRT discount / depeg event",
        "posisi looping di lending",
        "akhir window airdrop + likuiditas tipis"
      ],
      "scope": "Era restaking/LRT (2023–sekarang), saat leverage looping via lending market marak dan likuiditas sekunder LRT masih tipis. Bisa melemah jika desain LRT masa depan membatasi re-collateralization."
    },
    {
      "id": "P3",
      "nm": "Multi-token → Simplification",
      "triggers": [
        "multi-token"
      ],
      "instances": 2,
      "confidence": "MEDIUM",
      "analogs": [
        "Helium",
        "Synthetix"
      ],
      "src": "examples/CaseStudies/Batch-01-EvolutionAnalysis.md",
      "val": "",
      "pred": "Tokenomics multi-token yang rumit cenderung disederhanakan ke aset tunggal seiring project matang.",
      "watch": [
        "distorsi insentif antar-token",
        "beban kognitif user"
      ],
      "scope": "Lintas-era (diamati 2017–2025 di DeFi & DePIN) — tampak cukup timeless karena akar masalahnya (beban kognitif user, distorsi insentif) bukan fungsi kondisi pasar tertentu. Confidence tetap MEDIUM karena baru 2 instance."
    },
    {
      "id": "P4",
      "nm": "Airdrop-without-product → Post-TGE dump",
      "triggers": [
        "airdrop",
        "points"
      ],
      "instances": 2,
      "confidence": "MEDIUM",
      "analogs": [
        "ether.fi",
        "LayerZero",
        "Ethena"
      ],
      "src": "examples/CaseStudies/CrossAnalysis-ETH-Lido-EigenLayer.md",
      "val": "Renzo REZ (alokasi 5%, exit farmer pasca-window)",
      "pred": "Airdrop/points tanpa produk & usage nyata → farmer keluar pasca-TGE → tekanan jual. Airdrop dengan produk dominan lebih dulu (Uniswap/Hyperliquid) → retensi jauh lebih baik.",
      "watch": [
        "alokasi airdrop kecil/membingungkan",
        "aktivitas hanya untuk poin",
        "unlock/vesting pasca-TGE"
      ],
      "scope": "**Era-sensitif — jangan diterapkan buta.** Diamati 2020–2024 saat populasi airdrop-hunter masih tumbuh dan deteksi Sybil belum matang. Mekanisme \"task mudah → JP besar\" era 2021 (bridge-and-swap sederhana) TIDAK sebanding dengan era 2025–2026 (hunter jenuh, deteksi Sybil matang, task lebih rumit) — bandingkan Context (`docs/Ontology/Context.md`) target sebelum menerapkan, jangan hanya cocokkan mekanik permukaan."
    },
    {
      "id": "P5",
      "nm": "Technical success → Tokenomic harm",
      "triggers": [
        "fee-burn",
        "upgrade",
        "l2"
      ],
      "instances": 1,
      "confidence": "LOW",
      "analogs": [
        "Ethereum"
      ],
      "src": "examples/CaseStudies/Ethereum.md",
      "val": "ETH Dencun (2024) → net-inflasi",
      "pred": "Upgrade yang memindah aktivitas keluar dari mekanisme value-accrual bisa merusak tesis token walau sukses teknis.",
      "watch": [
        "burn/revenue turun pasca-upgrade"
      ],
      "scope": "Baru 1 instance (Ethereum/EIP-1559 era 2021–2024) — berlaku spesifik pada desain tokenomics yang value-accrual-nya terikat langsung ke throughput/kemacetan L1. Transferabilitas ke desain lain belum tervalidasi; confidence LOW sampai ada instance kedua."
    },
    {
      "id": "P6",
      "nm": "First-mover + standard = strongest moat",
      "triggers": [
        "first-mover",
        "smart-contract",
        "amm"
      ],
      "instances": 2,
      "confidence": "MEDIUM",
      "analogs": [
        "Ethereum",
        "Uniswap"
      ],
      "src": "examples/CaseStudies/Ethereum.md",
      "val": "",
      "pred": "First mover yang menjadi standar developer punya moat retensi terkuat, mengalahkan pesaing 'lebih cepat/murah'.",
      "watch": [
        "apakah pesaing mengadopsi standarnya"
      ],
      "scope": "Lintas-era (2015–sekarang) — bergantung pada adanya biaya migrasi developer yang nyata (tooling, likuiditas, efek jaringan), bukan pada kondisi pasar tertentu. Relatif timeless dibanding P4, tapi tetap MEDIUM karena baru 2 instance."
    }
  ],
  "sentiment": []
};
